TYPE_TEXT           = 'TEXT'
TYPE_CAT            = 'CAT'
TYPE_BOOL           = 'BOOL'
TYPE_NUM            = 'NUM'
TYPE_NUM_WITH_UNIT  = 'NUM_WITH_UNIT'
TYPE_DATE           = 'DATE'
TYPE_DATE_LIKE      = 'DATE_LIKE'
TYPE_CONST          = 'CONST'
